# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eslam Mostafa
subtitle: Lead. Inspire. Make a Difference.
email: cseslam@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Curious Software Engineer with passion to open-source and free software.
  Continously building & improving my CS fundamentals, making sure to be
  always ahead of what technology has to offer.
  <br><br>
  I have been playing with Python, Gtk+, C#, Sql, NodeJS for quite sometime now
  and looking forward to build libraries and tools in GoLang and study Machine
  Learning to make smarter applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://eslammostafa.github.io" # the base hostname & protocol for your site
# url: "http://localhost:4000" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  eslammostafa

# Build settings
markdown: kramdown
